apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-a-to-b
spec:
  podSelector:
    matchLabels:
      app: service-b
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: service-a
    ports:
    - protocol: TCP
      port: 80
  policyTypes:
  - Ingress